// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetPutPriceHandlerFunc turns a function with the right signature into a get put price handler
type GetPutPriceHandlerFunc func(GetPutPriceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPutPriceHandlerFunc) Handle(params GetPutPriceParams) middleware.Responder {
	return fn(params)
}

// GetPutPriceHandler interface for that can handle valid get put price params
type GetPutPriceHandler interface {
	Handle(GetPutPriceParams) middleware.Responder
}

// NewGetPutPrice creates a new http.Handler for the get put price operation
func NewGetPutPrice(ctx *middleware.Context, handler GetPutPriceHandler) *GetPutPrice {
	return &GetPutPrice{Context: ctx, Handler: handler}
}

/*GetPutPrice swagger:route GET /putPrice financeapi getPutPrice

GetPutPrice get put price API

*/
type GetPutPrice struct {
	Context *middleware.Context
	Handler GetPutPriceHandler
}

func (o *GetPutPrice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPutPriceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetPutPriceBody get put price body
//
// swagger:model GetPutPriceBody
type GetPutPriceBody struct {

	// value between 0 and 1
	RiskFreeRate float64 `json:"risk-free-rate,omitempty"`

	// volatility as a value between 0 and 1
	Sigma float64 `json:"sigma,omitempty"`

	// spot price
	SpotPrice float64 `json:"spot-price,omitempty"`

	// strike price
	StrikePrice float64 `json:"strike-price,omitempty"`

	// time to maturity in years
	TimeToMaturity float64 `json:"time-to-maturity,omitempty"`
}

// Validate validates this get put price body
func (o *GetPutPriceBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetPutPriceBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetPutPriceBody) UnmarshalBinary(b []byte) error {
	var res GetPutPriceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
