// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"fmt"
	"math"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"gonum.org/v1/gonum/stat/distuv"
)

// GetCallPriceHandlerFunc turns a function with the right signature into a get call price handler
type GetCallPriceHandlerFunc func(GetCallPriceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCallPriceHandlerFunc) Handle(params GetCallPriceParams) middleware.Responder {
	fmt.Println(params.CallPrice.RiskFreeRate)
	call_price, err := blackscholes(params.CallPrice.TimeToMaturity, params.CallPrice.SpotPrice, params.CallPrice.StrikePrice, params.CallPrice.RiskFreeRate, params.CallPrice.Sigma)
	fmt.Println(call_price)
	fmt.Println(err)
	resp_ok := NewGetCallPriceOK()
	resp_ok.SetPayload(call_price)
	return resp_ok
}

// blackscholes calculates option prices
// Arguments:
// float time_to_mat -> time to maturity
// float spot -> spot price of underlying asset
// float strike -> strike price
// float risk_free -> risk free rate
// float sig -> volatility of underlying asset
// Returns:
// float c -> call price
func blackscholes(time_to_mat float64, spot float64, strike float64, risk_free float64, sig float64) (float64, error) {

	//check if any negativce values were provided
	if time_to_mat < 0 || spot < 0 || strike < 0 || risk_free < 0 || sig < 0 {
		return -1, errors.New("Provided negaitve number as arsgument to blackscholes")
	}
	//check if risk_free rate and volatility value percentage between 0,1
	if risk_free > 1.0 || sig > 1.0 {
		return -1, errors.New("percentage value not in the range between 0 and 1")
	}

	//define standart normal distribution
	norm_dist := distuv.Normal{
		Mu:    0,
		Sigma: 1,
	}
	// black scholes formulas SEE: https://en.wikipedia.org/wiki/Black%E2%80%93Scholes_model
	d1 := 1 / (sig * math.Sqrt(time_to_mat)) * (math.Log(spot/strike) + (risk_free+math.Pow(sig, 2)/2)*time_to_mat)
	d2 := d1 - sig*math.Sqrt(time_to_mat)
	pv := strike * math.Exp(-risk_free*time_to_mat)
	call_price := norm_dist.CDF(d1)*spot - norm_dist.CDF(d2)*pv

	return call_price, nil

}

// GetCallPriceHandler interface for that can handle valid get call price params
type GetCallPriceHandler interface {
	Handle(GetCallPriceParams) middleware.Responder
}

// NewGetCallPrice creates a new http.Handler for the get call price operation
func NewGetCallPrice(ctx *middleware.Context, handler GetCallPriceHandler) *GetCallPrice {
	return &GetCallPrice{Context: ctx, Handler: handler}
}

/*GetCallPrice swagger:route GET /callPrice financeapi getCallPrice

GetCallPrice get call price API

*/
type GetCallPrice struct {
	Context *middleware.Context
	Handler GetCallPriceHandler
}

func (o *GetCallPrice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCallPriceParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetCallPriceBody get call price body
//
// swagger:model GetCallPriceBody
type GetCallPriceBody struct {

	// value between 0 and 1
	RiskFreeRate float64 `json:"risk-free-rate,omitempty"`

	// volatility as a value between 0 and 1
	Sigma float64 `json:"sigma,omitempty"`

	// spot price
	SpotPrice float64 `json:"spot-price,omitempty"`

	// strike price
	StrikePrice float64 `json:"strike-price,omitempty"`

	// time to maturity in years
	TimeToMaturity float64 `json:"time-to-maturity,omitempty"`
}

// Validate validates this get call price body
func (o *GetCallPriceBody) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetCallPriceBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetCallPriceBody) UnmarshalBinary(b []byte) error {
	var res GetCallPriceBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
