// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPutPriceHandlerFunc turns a function with the right signature into a get put price handler
type GetPutPriceHandlerFunc func(GetPutPriceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPutPriceHandlerFunc) Handle(params GetPutPriceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetPutPriceHandler interface for that can handle valid get put price params
type GetPutPriceHandler interface {
	Handle(GetPutPriceParams, interface{}) middleware.Responder
}

// NewGetPutPrice creates a new http.Handler for the get put price operation
func NewGetPutPrice(ctx *middleware.Context, handler GetPutPriceHandler) *GetPutPrice {
	return &GetPutPrice{Context: ctx, Handler: handler}
}

/*GetPutPrice swagger:route GET /putPrice financeapi getPutPrice

GetPutPrice get put price API

*/
type GetPutPrice struct {
	Context *middleware.Context
	Handler GetPutPriceHandler
}

func (o *GetPutPrice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPutPriceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
