// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/gofinance/models"
)

// NewGetPutPriceParams creates a new GetPutPriceParams object
// no default values defined in spec.
func NewGetPutPriceParams() GetPutPriceParams {

	return GetPutPriceParams{}
}

// GetPutPriceParams contains all the bound params for the get put price operation
// typically these are obtained from a http.Request
//
// swagger:parameters get_put_price
type GetPutPriceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*calculates put price
	  In: body
	*/
	PutPrice *models.OptionPrice
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetPutPriceParams() beforehand.
func (o *GetPutPriceParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.OptionPrice
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("putPrice", "body", "", err))
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.PutPrice = &body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
