// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gofinance/models"
)

// GetCallPriceOKCode is the HTTP code returned for type GetCallPriceOK
const GetCallPriceOKCode int = 200

/*GetCallPriceOK calculate Call price of option

swagger:response getCallPriceOK
*/
type GetCallPriceOK struct {

	/*call price
	  In: Body
	*/
	Payload float64 `json:"body,omitempty"`
}

// NewGetCallPriceOK creates GetCallPriceOK with default headers values
func NewGetCallPriceOK() *GetCallPriceOK {

	return &GetCallPriceOK{}
}

// WithPayload adds the payload to the get call price o k response
func (o *GetCallPriceOK) WithPayload(payload float64) *GetCallPriceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get call price o k response
func (o *GetCallPriceOK) SetPayload(payload float64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallPriceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetCallPriceDefault generic error response

swagger:response getCallPriceDefault
*/
type GetCallPriceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCallPriceDefault creates GetCallPriceDefault with default headers values
func NewGetCallPriceDefault(code int) *GetCallPriceDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCallPriceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get call price default response
func (o *GetCallPriceDefault) WithStatusCode(code int) *GetCallPriceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get call price default response
func (o *GetCallPriceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get call price default response
func (o *GetCallPriceDefault) WithPayload(payload *models.Error) *GetCallPriceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get call price default response
func (o *GetCallPriceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCallPriceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
