// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gofinance/models"
)

// GetPutPriceOKCode is the HTTP code returned for type GetPutPriceOK
const GetPutPriceOKCode int = 200

/*GetPutPriceOK calculate Call price of option

swagger:response getPutPriceOK
*/
type GetPutPriceOK struct {

	/*call price
	  In: Body
	*/
	Payload float64 `json:"body,omitempty"`
}

// NewGetPutPriceOK creates GetPutPriceOK with default headers values
func NewGetPutPriceOK() *GetPutPriceOK {

	return &GetPutPriceOK{}
}

// WithPayload adds the payload to the get put price o k response
func (o *GetPutPriceOK) WithPayload(payload float64) *GetPutPriceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get put price o k response
func (o *GetPutPriceOK) SetPayload(payload float64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPutPriceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetPutPriceDefault generic error response

swagger:response getPutPriceDefault
*/
type GetPutPriceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPutPriceDefault creates GetPutPriceDefault with default headers values
func NewGetPutPriceDefault(code int) *GetPutPriceDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPutPriceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get put price default response
func (o *GetPutPriceDefault) WithStatusCode(code int) *GetPutPriceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get put price default response
func (o *GetPutPriceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get put price default response
func (o *GetPutPriceDefault) WithPayload(payload *models.Error) *GetPutPriceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get put price default response
func (o *GetPutPriceDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPutPriceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
