// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCallPriceHandlerFunc turns a function with the right signature into a get call price handler
type GetCallPriceHandlerFunc func(GetCallPriceParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCallPriceHandlerFunc) Handle(params GetCallPriceParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetCallPriceHandler interface for that can handle valid get call price params
type GetCallPriceHandler interface {
	Handle(GetCallPriceParams, interface{}) middleware.Responder
}

// NewGetCallPrice creates a new http.Handler for the get call price operation
func NewGetCallPrice(ctx *middleware.Context, handler GetCallPriceHandler) *GetCallPrice {
	return &GetCallPrice{Context: ctx, Handler: handler}
}

/*GetCallPrice swagger:route GET /callPrice financeapi getCallPrice

GetCallPrice get call price API

*/
type GetCallPrice struct {
	Context *middleware.Context
	Handler GetCallPriceHandler
}

func (o *GetCallPrice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCallPriceParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
