// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// MovingaverageHandlerFunc turns a function with the right signature into a movingaverage handler
type MovingaverageHandlerFunc func(MovingaverageParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn MovingaverageHandlerFunc) Handle(params MovingaverageParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// MovingaverageHandler interface for that can handle valid movingaverage params
type MovingaverageHandler interface {
	Handle(MovingaverageParams, interface{}) middleware.Responder
}

// NewMovingaverage creates a new http.Handler for the movingaverage operation
func NewMovingaverage(ctx *middleware.Context, handler MovingaverageHandler) *Movingaverage {
	return &Movingaverage{Context: ctx, Handler: handler}
}

/*Movingaverage swagger:route GET /movingaverage financeapi movingaverage

Movingaverage movingaverage API

*/
type Movingaverage struct {
	Context *middleware.Context
	Handler MovingaverageHandler
}

func (o *Movingaverage) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewMovingaverageParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
