// Code generated by go-swagger; DO NOT EDIT.

package financeapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gofinance/models"
)

// MovingaverageOKCode is the HTTP code returned for type MovingaverageOK
const MovingaverageOKCode int = 200

/*MovingaverageOK returns moving average

swagger:response movingaverageOK
*/
type MovingaverageOK struct {

	/*movingaverage datas
	  In: Body
	*/
	Payload []float64 `json:"body,omitempty"`
}

// NewMovingaverageOK creates MovingaverageOK with default headers values
func NewMovingaverageOK() *MovingaverageOK {

	return &MovingaverageOK{}
}

// WithPayload adds the payload to the movingaverage o k response
func (o *MovingaverageOK) WithPayload(payload []float64) *MovingaverageOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the movingaverage o k response
func (o *MovingaverageOK) SetPayload(payload []float64) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MovingaverageOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]float64, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*MovingaverageDefault generic error response

swagger:response movingaverageDefault
*/
type MovingaverageDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMovingaverageDefault creates MovingaverageDefault with default headers values
func NewMovingaverageDefault(code int) *MovingaverageDefault {
	if code <= 0 {
		code = 500
	}

	return &MovingaverageDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the movingaverage default response
func (o *MovingaverageDefault) WithStatusCode(code int) *MovingaverageDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the movingaverage default response
func (o *MovingaverageDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the movingaverage default response
func (o *MovingaverageDefault) WithPayload(payload *models.Error) *MovingaverageDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the movingaverage default response
func (o *MovingaverageDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MovingaverageDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
