// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Finance API
//
//  Finance api which implements common operations
//  Schemes:
//    http
//    https
//  Host: localhost
//  BasePath: /v1
//  Version: 1.0.0
//  Contact: <gretler.tim@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
