// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Finance api which implements common operations",
    "title": "Finance API",
    "contact": {
      "email": "gretler.tim@gmail.com"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/callPrice": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "parameters": [
          {
            "description": "calculates call price",
            "name": "callPrice",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "risk-free-rate": {
                  "description": "value between 0 and 1",
                  "type": "number"
                },
                "sigma": {
                  "description": "volatility as a value between 0 and 1",
                  "type": "number"
                },
                "spot-price": {
                  "type": "number"
                },
                "strike-price": {
                  "type": "number"
                },
                "time-to-maturity": {
                  "description": "time to maturity in years",
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "calculate Call price of option",
            "schema": {
              "description": "call price",
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/putPrice": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "parameters": [
          {
            "description": "calculates call price",
            "name": "callPrice",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "risk-free-rate": {
                  "description": "value between 0 and 1",
                  "type": "number"
                },
                "sigma": {
                  "description": "volatility as a value between 0 and 1",
                  "type": "number"
                },
                "spot-price": {
                  "type": "number"
                },
                "strike-price": {
                  "type": "number"
                },
                "time-to-maturity": {
                  "description": "time to maturity in years",
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "calculate Call price of option",
            "schema": {
              "description": "call price",
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Finance api which implements common operations",
    "title": "Finance API",
    "contact": {
      "email": "gretler.tim@gmail.com"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/callPrice": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "parameters": [
          {
            "description": "calculates call price",
            "name": "callPrice",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "risk-free-rate": {
                  "description": "value between 0 and 1",
                  "type": "number"
                },
                "sigma": {
                  "description": "volatility as a value between 0 and 1",
                  "type": "number"
                },
                "spot-price": {
                  "type": "number"
                },
                "strike-price": {
                  "type": "number"
                },
                "time-to-maturity": {
                  "description": "time to maturity in years",
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "calculate Call price of option",
            "schema": {
              "description": "call price",
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/putPrice": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "parameters": [
          {
            "description": "calculates call price",
            "name": "callPrice",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "risk-free-rate": {
                  "description": "value between 0 and 1",
                  "type": "number"
                },
                "sigma": {
                  "description": "volatility as a value between 0 and 1",
                  "type": "number"
                },
                "spot-price": {
                  "type": "number"
                },
                "strike-price": {
                  "type": "number"
                },
                "time-to-maturity": {
                  "description": "time to maturity in years",
                  "type": "number"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "calculate Call price of option",
            "schema": {
              "description": "call price",
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
