// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Finance api which implements common operations",
    "title": "Finance API",
    "contact": {
      "email": "gretler.tim@gmail.com"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/callPrice": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "operationId": "get_call_price",
        "parameters": [
          {
            "description": "calculates call price",
            "name": "callPrice",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/option-price"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "return call price",
            "schema": {
              "description": "call price",
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/movingaverage": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "operationId": "movingaverage",
        "parameters": [
          {
            "description": "calculates movingaverage",
            "name": "movingaverage",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/movingaverage-input"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns moving average",
            "schema": {
              "description": "movingaverage datas",
              "type": "array",
              "items": {
                "type": "number"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/putPrice": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "operationId": "get_put_price",
        "parameters": [
          {
            "description": "calculates put price",
            "name": "putPrice",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/option-price"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "return put price",
            "schema": {
              "description": "put price",
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "movingaverage-input": {
      "type": "object",
      "required": [
        "time-data",
        "point-to-avg"
      ],
      "properties": {
        "point-to-avg": {
          "type": "integer"
        },
        "time-data": {
          "type": "array",
          "items": {
            "type": "number"
          }
        }
      }
    },
    "option-price": {
      "type": "object",
      "required": [
        "time-to-maturity",
        "spot-price",
        "risk-free-rate",
        "sigma",
        "strike-price"
      ],
      "properties": {
        "risk-free-rate": {
          "description": "value between 0 and 1",
          "type": "number"
        },
        "sigma": {
          "description": "volatility as a value between 0 and 1",
          "type": "number"
        },
        "spot-price": {
          "type": "number"
        },
        "strike-price": {
          "type": "number"
        },
        "time-to-maturity": {
          "description": "time to maturity in years",
          "type": "number"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "apikey": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    },
    "basicAuth": {
      "type": "basic"
    }
  },
  "security": [
    {
      "basicAuth": []
    },
    {
      "apikey": []
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Finance api which implements common operations",
    "title": "Finance API",
    "contact": {
      "email": "gretler.tim@gmail.com"
    },
    "version": "1.0.0"
  },
  "basePath": "/v1",
  "paths": {
    "/callPrice": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "operationId": "get_call_price",
        "parameters": [
          {
            "description": "calculates call price",
            "name": "callPrice",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/option-price"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "return call price",
            "schema": {
              "description": "call price",
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/movingaverage": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "operationId": "movingaverage",
        "parameters": [
          {
            "description": "calculates movingaverage",
            "name": "movingaverage",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/movingaverage-input"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "returns moving average",
            "schema": {
              "description": "movingaverage datas",
              "type": "array",
              "items": {
                "type": "number"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/putPrice": {
      "get": {
        "tags": [
          "financeapi"
        ],
        "operationId": "get_put_price",
        "parameters": [
          {
            "description": "calculates put price",
            "name": "putPrice",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/option-price"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "return put price",
            "schema": {
              "description": "put price",
              "type": "number"
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "movingaverage-input": {
      "type": "object",
      "required": [
        "time-data",
        "point-to-avg"
      ],
      "properties": {
        "point-to-avg": {
          "type": "integer"
        },
        "time-data": {
          "type": "array",
          "items": {
            "type": "number"
          }
        }
      }
    },
    "option-price": {
      "type": "object",
      "required": [
        "time-to-maturity",
        "spot-price",
        "risk-free-rate",
        "sigma",
        "strike-price"
      ],
      "properties": {
        "risk-free-rate": {
          "description": "value between 0 and 1",
          "type": "number"
        },
        "sigma": {
          "description": "volatility as a value between 0 and 1",
          "type": "number"
        },
        "spot-price": {
          "type": "number"
        },
        "strike-price": {
          "type": "number"
        },
        "time-to-maturity": {
          "description": "time to maturity in years",
          "type": "number"
        }
      }
    },
    "principal": {
      "type": "string"
    }
  },
  "securityDefinitions": {
    "apikey": {
      "type": "apiKey",
      "name": "x-token",
      "in": "header"
    },
    "basicAuth": {
      "type": "basic"
    }
  },
  "security": [
    {
      "basicAuth": []
    },
    {
      "apikey": []
    }
  ]
}`))
}
