// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MovingaverageInput movingaverage input
//
// swagger:model movingaverage-input
type MovingaverageInput struct {

	// point to avg
	// Required: true
	PointToAvg *int64 `json:"point-to-avg"`

	// time data
	// Required: true
	TimeData []float64 `json:"time-data"`
}

// Validate validates this movingaverage input
func (m *MovingaverageInput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePointToAvg(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimeData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MovingaverageInput) validatePointToAvg(formats strfmt.Registry) error {

	if err := validate.Required("point-to-avg", "body", m.PointToAvg); err != nil {
		return err
	}

	return nil
}

func (m *MovingaverageInput) validateTimeData(formats strfmt.Registry) error {

	if err := validate.Required("time-data", "body", m.TimeData); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MovingaverageInput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MovingaverageInput) UnmarshalBinary(b []byte) error {
	var res MovingaverageInput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
